version: "3.9"

services:
  tshock:
    build: .
    cap_drop: [ "ALL" ]
    init: true

    tty: true
    stdin_open: true

    environment:
      - "TERRARIA_EXTRA_PARAMS=-secure"
      - "TERRARIA_WORLD_SIZE=3"
    volumes:
      - ./data:/data
      - ./data/plugins:/data/plugins:ro

    ports:
      - "7777:7777"
    restart: unless-stopped
